displayName=Quest Requirement Tracker
author=Dehmahk
description=Tracks skill requirements for quests and shows how many levels you need to complete them.
tags=quest,skills,tracker,requirements
version=1
plugins=com.QuestTracker.QuestRequirementTrackerPlugin
build=standard

